### ISSUE TITLE
Read about and decide on the Agile practice. # due Week 1

### ISSUE THREAD

**Issue by amit-sjsu** [amit-sjsu/SWAT-Kats#10]

**Comment by shafi-dayatar** [comment]
Do we need to write which agile practice we will be using and why???

**Comment by navneetjain90** [comment]
I think we don't have any option. 
Kanban is the one which we will be using

**Comment by amit-sjsu** [comment]
Naveent you are correct, we do not have option to choose the agile process. We need to go with Kanban.

**Comment by shafi-dayatar** [comment]
![screenshot from 2016-09-17 11 24 33](https://cloud.githubusercontent.com/assets/3094886/18610208/d7634456-7cca-11e6-93af-23b77f0f69f4.png)

We can use our own!! we can mix up scrum and kanban.

**Comment by shafi-dayatar** [comment]
Till what i have understood, we can use XP methodology for development maintenance of project, with kanban for generating and maintaining task and scrum to keep a track on the task/issue.

**Comment by shafi-dayatar** [comment]
And this will be mentioned in Workflow or Team Principles right?

**Comment by navneetjain90** [comment]
Sekected Kanban with a mix of Scrum.

**Comment by shafi-dayatar** [comment]
Can you write a brief description about it? why we are using this methodology or part of it?
