### ISSUE TITLE
Decide on Greenfoot or Processing. #due Week 1

### ISSUE THREAD

**Issue by SwathiKoduri** [amit-sjsu/SWAT-Kats#11]
Learn about both the tools and decide on one based on which will be more suitable for our activity.

**Comment by shafi-dayatar** [comment]
I have mail you link about it on your sjsu mail.
Kindly look and add what you like.

**Comment by navneetjain90** [comment]
My vote will be with Greenfoot

**Comment by amit-sjsu** [comment]
I would also suggest to go with Greenfoot .

**Comment by amit-sjsu** [comment]
Guys, I think this issue was due for week 1. Lets us decide on the technology ASAP.

**Comment by SwathiKoduri** [comment]
We have decided on Greenfoot for the project
