### ISSUE TITLE
Learn and Setup Processing. #due Week 1

### ISSUE THREAD

**Issue by shafi-dayatar** [amit-sjsu/SWAT-Kats#14]
Learn about processing, Why it is used. Steps to install it. Pros and Cons of Processing.

**Comment by navneetjain90** [comment]
Done from my end

**Comment by shafi-dayatar** [comment]
We can move this to done!!!!

**Comment by amit-sjsu** [comment]
I think learning and setup of processing has been done by everyone.
Moving this issue to done.
