### ISSUE TITLE
Week 1:- Report submission

### ISSUE THREAD

**Issue by navneetjain90** [amit-sjsu/SWAT-Kats#15]
A report needs to be created with all the details mentioned in the document and submitted on canvas before September 18,2016 11:59PM.

**Comment by shafi-dayatar** [comment]
Weekly Submissions

Submissions will be "one per team" (per section), but grading will be made on an individual basis.
Upload a PDF with the following:
Title Page with:
Note:  Please include your Project Group #1 on the First Submission.
Team Name (as declared on Canvas)
Names of each Team Member (with CMPE 202 Section Number)
IDs of teach Team Members GitHub account.
Link to Team's GitHub Repository.  Note: Team members are expected to make weekly commits.
Link to Team's Task Board.  Note: All Backlog Items "In Progress" must be assigned to a team member.
Link to Teams Kanban CFD Google Sheet.
Journal Entries from all team members (one page per team member)
This should be a consolidation of individual work from each team member

**Comment by shafi-dayatar** [comment]
I will create a title page of the Week1 Submission !!!
It will be available by tomorrow night.

And Link to Teams Kanban CFD Google Sheet. I think we will have to give read access to this link or read access for professor :)  Can anyone create a issue for this and Anudeep you take up this task.

**Comment by shafi-dayatar** [comment]
"Journal Entries from all team members (one page per team member)" This is a individual task. Shouldnt we create a task for each team member? 
What do you think guys !!!!

Note  this is not a group task!!!

**Comment by SwathiKoduri** [comment]
yeah.. i think we can create individual tasks.. and i will create one more task for submitting the whole report

**Comment by SwathiKoduri** [comment]
submission done
