### ISSUE TITLE
Research about activities: Algorithms: Putting Computers to Work #due Week 1

### ISSUE THREAD

**Issue by shafi-dayatar** [amit-sjsu/SWAT-Kats#16]
There are nine activities, come up with a story that can be converted to a multiplayer game.

**Comment by navneetjain90** [comment]
I am taking up this activity and will upload a document describing all the mentioned activities.

**Comment by navneetjain90** [comment]
1.Sorting networks
2. Divide and conquer :- Any of these two can be picked from this pool.
