### ISSUE TITLE
Deciding team name

### ISSUE THREAD

**Issue by amit-sjsu** [amit-sjsu/SWAT-Kats#2]
Lets meet on Monday , Sep 12   11 :00 am to decide team name.

**Comment by shafi-dayatar** [comment]
If anyone finds a name for the team they can comment here!!!!
How about "Awesomers"? What do you think guys ????

**Comment by rentala** [comment]
I don't know if that is even a real word :) 
How about Spartans ? Alt-Tab ? Rocket ?

**Comment by navneetjain90** [comment]
Shafi :- Awesomers, SwatKats
Anudeep :- Rockets, Team Titans
 Navneet :- Team Incognito

 Team Name Finalized :- SWAT Kats: The Radical Squadron

**Comment by amit-sjsu** [comment]
The Radical Squadron is removed. 
Final Team name is :- SWAT Kats
