### ISSUE TITLE
Create Team Principles. #due Week 2

### ISSUE THREAD

**Issue by rentala** [amit-sjsu/SWAT-Kats#21]
This task is to help create a document that provides the guidelines for process in the team.

**Comment by rentala** [comment]
Use #tags to add deadlines to issues in title as seen above.

**Comment by rentala** [comment]
We havent made any progress on this yet, should we shelve it ?

**Comment by navneetjain90** [comment]
Will start putting some entries in this now onwards

**Comment by shafi-dayatar** [comment]
Can you guys review it ?
