### ISSUE TITLE
Create WebEx meeting #Week 1

### ISSUE THREAD

**Issue by amit-sjsu** [amit-sjsu/SWAT-Kats#22]
next meeting is to be done over WebEx. Creating a WebEx Platform will help  every one  to join the  meeting from his or her desire place.

**Comment by amit-sjsu** [comment]
lets make  this sunday meeting on webEx.

**Comment by amit-sjsu** [comment]
lets make  this sunday meeting on webEx.

**Comment by amit-sjsu** [comment]
Navneet , we need to set up webEx meeting , it would help us to meet up on a regular basis,
lets not delay on this issue any more and try to do it as early as possible

**Comment by navneetjain90** [comment]
This has already been done and link was posted on the group. Try to search for UberConference and u will get the access details. There is a meeting scheduled for today @ 11PM

**Comment by rentala** [comment]
Meeting done and Minutes of Meeting to be posted shortly on Git.
