### ISSUE TITLE
Remove Midnight-Jam from Collaborators

### ISSUE THREAD

**Issue by shafi-dayatar** [amit-sjsu/SWAT-Kats#23]
Amit you have to remove from collaborators.

**Comment by amit-sjsu** [comment]
Midnight -Jam is not a Collaborator.  What you can see in git hub is his commit which was done by  him on the first day as  guest contributor.

**Comment by shafi-dayatar** [comment]
This wont create a problem right!!!

**Comment by amit-sjsu** [comment]
No it should not however I am trying to remove his commit from github.

**Comment by shafi-dayatar** [comment]
Cool!!! Thanks for the help dude!!!
