### ISSUE TITLE
Find target audience and try sampling ideas #due31st Oct

### ISSUE THREAD

**Issue by rentala** [amit-sjsu/SWAT-Kats#27]
Find an audience to try a prototype our game and gain feedback.

**Comment by shafi-dayatar** [comment]
We are done with this right ???

**Comment by shafi-dayatar** [comment]
Done right ???? Shouldn't we move this done ?

**Comment by rentala** [comment]
I think this should be renamed and rephrased - to demoing prototype or MVP to external audience. What do you guys think ?
