### ISSUE TITLE
Journal Entry- Courage

### ISSUE THREAD

**Issue by shafi-dayatar** [amit-sjsu/SWAT-Kats#31]
Have to write about Courage and how does our team maintain this.

**Comment by amit-sjsu** [comment]
you should look for things which is not happening in the team as per courage and try to fill the gap by brings those things in the team. If anyone is hesitating to bring his idea or  if  to meet the deadline if any one is trying methods which he/she must not try, you should let him know about it and help him to get the things done in write way.

**Comment by shafi-dayatar** [comment]
Moving it to Done!!!
