### ISSUE TITLE
Use case diagram for the game #due 4th Oct

### ISSUE THREAD

**Issue by navneetjain90** [amit-sjsu/SWAT-Kats#33]
This will explain the actors and the actions an actor can perform

**Comment by navneetjain90** [comment]
Everyone write one use case diagram for the game which we had discussed and in next meeting we will come up with a common use case diagram.

**Comment by amit-sjsu** [comment]
uploaded a use case diagram and astah file in github

**Comment by shafi-dayatar** [comment]
Done!!! Are changes Committed?
