### ISSUE TITLE
Activity diagram for the game #due 29th Sept

### ISSUE THREAD

**Issue by rentala** [amit-sjsu/SWAT-Kats#35]

**Comment by navneetjain90** [comment]
Everyone write activity diagram for the game which we had discussed and in next meeting we will come up with a common use case diagram.
Can be done on page but preferred with Astah UML

**Comment by shafi-dayatar** [comment]
This is done right?

**Comment by shafi-dayatar** [comment]
Done!!!
Changes are committed???
