### ISSUE TITLE
Create just environment and nodes on greenfoot.

### ISSUE THREAD

**Issue by navneetjain90** [amit-sjsu/SWAT-Kats#37]
Start coding to create an environment and nodes on the greenfoot.  (Basically its actually designing the objects on the screen)

**Comment by shafi-dayatar** [comment]
Could you please explain me what does node means here???

**Comment by rentala** [comment]
Yea Im not sure I understand this task either

**Comment by navneetjain90** [comment]
Actually at that time I was thinking something else... We can take care of this latter on
