### ISSUE TITLE
Create Class diagram for the Game

### ISSUE THREAD

**Issue by navneetjain90** [amit-sjsu/SWAT-Kats#43]

**Comment by shafi-dayatar** [comment]
I think we should have a gameLayoutManager as class and it should have all the methods and attributes that will help GameController/Game to add/modify/delete objects that is (house/roads ..etc) in game!!!!

**Comment by shafi-dayatar** [comment]
This is a must read !! https://drive.google.com/file/d/0ByOwmqah_nuGNHEtcU5OekdDMkk/view

**Comment by rentala** [comment]
Thanks Shafi, I added the class diagram in github, let me know what you think about it.
