### ISSUE TITLE
As a player, when I select the paths between houses and click on validate, I should get a response on the UI indicating whether my path was the shortest or not #UserStories

### ISSUE THREAD

**Issue by rentala** [amit-sjsu/SWAT-Kats#57]
Contract:

interface PathSetter{
  public boolean IsShortesPath(List<Path> SelectedPath);

  public Collection GetShortestPath(List<Path> AllPaths);

}

Required:

Class path should contain x-y coordinates for starting point of a path and ending point of a path.
Class path should contain the two House objects that the path contains

**Comment by rentala** [comment]
Code checked in, integration pending

**Comment by rentala** [comment]
Intgrated, testing pending

**Comment by shafi-dayatar** [comment]
Its Done.
