### ISSUE TITLE
Deciding the CS Unplugged activity which will be built for the final team project

### ISSUE THREAD

**Issue by navneetjain90** [amit-sjsu/SWAT-Kats#6]

**Comment by amit-sjsu** [comment]
In  Procedures: Telling Computers What to Do I found Finite State Automata to be interesting one, we should give a thought about it.

**Comment by navneetjain90** [comment]
This will be decided in today's meeting.

**Comment by navneetjain90** [comment]
Narrow down to Minimal Spanning Tree and Finite State Automata

**Comment by rentala** [comment]
- Harold the robot

**Comment by rentala** [comment]
All three ideas have been sent to Professor for feedback

**Comment by shafi-dayatar** [comment]
Did you cc that mail to our email addresses?

**Comment by navneetjain90** [comment]
Minimal spanning tree has been finalized. A game of building the roads of a muddy town with the minimum cost will be developed.

**Comment by shafi-dayatar** [comment]
Moving it to done!!!
