### ISSUE TITLE
Learn and Setup Greenfoot.

### ISSUE THREAD

**Issue by amit-sjsu** [amit-sjsu/SWAT-Kats#9]
Learn and setup Greenfoot for project requirement . Document your learning (optional).

**Comment by shafi-dayatar** [comment]
Why it is labeled as invalid? Does anyone know about it ?

**Comment by navneetjain90** [comment]
Done from my end

**Comment by amit-sjsu** [comment]
learning and setup done from my end.

**Comment by shafi-dayatar** [comment]
Can we move this to done???

**Comment by navneetjain90** [comment]
Everybody is done with the Lab 1 assignment and so they have an Idea of Green foot. Moving it to done now.
